### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JimmyRowland** [JimmyRowland/team_sporty#23]
- [x] remove background color for new post textarea
- [x] bigger icons
- [ ] Use moment to format time https://momentjs.com/
- [ ] Edit team page
- [ ] Search function for players
- [x] Dynamically add static paths (The path to new team page currently gives 404)
- [ ] Sprucing up the team page, announcements on team page. Need to make the page responsive
- [ ] change password.
- [x] lazyquery and loading components. Need to find a good loading components
- [ ] Make all pages responsive
- [x] comment server. 
- [ ] GoogleMap auto complete. Googlemap.

**Comment by JimmyRowland** [comment]
- [ ] Ability to add profile image and cover image
- [ ] need component - Bill
- [ ] Manage teams - promote players to coaches/managers; kick players
- [ ] need comlponent - Yu Tian is currently working on it
- [ ] pass ID of member
- [ ] Search function for teams (moved to stretch)
- [ ] Join teams/team portal
- [ ] need component to do the request (member pending list who have requested to join the team) - Yu Tian is working on that
- [ ] coaches and players in two separate lists in the team member map
- [ ] Mark off availability for events - geordie
- [ ] needs to be connected to the DB
- [ ] Sprucing up the team page, announcements on team page
- [ ] finish the team page - Collin, fixing console bugs; input validation (team topics)
- [ ] Dynamic routing
- [ ] :( -- ??? - is it necessary?
- [ ] try it after with team pages (not necessary for anything else)
- [ ] for teams, a specific page will be different depending whose team page you are on
- [ ] SSR
- [ ] server side rendering
- [ ] nextJS - already done
- [ ] Deployment
- [ ] ask TAs and instructors on Thursday
- [ ] Stretch
- [ ] search function for teams (Yu Tian is working on it)
- [ ] Managing Clubs (can have more than one team in a club)
- [ ] Sports Statistics (individual and team)
- [ ] Direct messages to individuals
- [ ] Search function for players
- [ ] Add images to message board
- [ ] 
- [ ] - [ ]

**Comment by engineereng** [comment]
Bill: registerpage

**Comment by JimmyRowland** [comment]
Strech
- [ ] Page transitions
- [ ] Email conformation page
- [ ] Direct messages to individuals
- [ ] Managing Clubs (can have more than one team in a club)
- [ ] Sports Statistics (individual and team)

**Comment by engineereng** [comment]
- [ ] Add input validation to register page (with appropriate feedback)
